[book]
authors = ["JordiMateoUdL"]
language = "ca"
multilingual = false
src = "src"
title = "Laboratoris de Sistemes Operatius per a estudiants del Grau en Enginyeria Informàtica"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/OS-GEI-IGUALADA-2425/laboratoris"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true

[output.html.code.hidelines]
sh = "~"
c = "~"
plaintext = "~"

